package logic;

public enum Ergebnisse {
    DREIERPASCH, CHANCE, FULLHOUSE, 
    GROSSESTRASSE, KLEINESTRASSE, KNIFFEL, 
    QUADRATFOLGE, VIERERPASCH, EINER, ZWEIER, 
    DREIER, VIERER, FÜNFER, SECHSER
}
